#!/bin/bash -e

readonly COMPONENT=docs
readonly ONEBOX_NAME="$COMPONENT"_onebox
readonly PORT=5555
readonly CYAN="\e[96m"
readonly RESET="\e[39m"

log.info() {
  echo -e "$CYAN" "$@" "$RESET"
}

log.verbose() {
  echo -e $"@"
}

docker-stop() {
  local onebox_exist; onebox_exist=$(docker ps -a | grep $ONEBOX_NAME | awk '{print $1}')
  if [[ -n $onebox_exist ]]; then
    log.info "Removing $COMPONENT container..."
    docker rm -f $ONEBOX_NAME >/dev/null
  fi
}

docker-build() {
  log.info "Building $COMPONENT image..."
  docker build -t shipimg/$COMPONENT .
}

docker-run() {
  log.info "Running $COMPONENT..."
  docker run --name=$ONEBOX_NAME \
    -d -p $PORT:$PORT \
    -v "$(pwd):/home/shippable/$COMPONENT:rw" \
    -t shipimg/$COMPONENT \
    >/dev/null

  log.verbose "Running at http://localhost:$PORT"
}

main() {
  docker-stop
  docker-build
  docker-run
}

main
